[dev]
  command="yarn workspace website dev"

[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.19"
  NODE_VERSION = "18.12.1"

[build]
  command = "yarn workspace website build"
  publish = "website/build"
